# app/src/module/audio_player/audio_hardware.py
from typing import Protocol

class AudioPlayerHardware(Protocol):
    def play(self, track: str) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def set_volume(self, volume: float) -> None: ...
    def cleanup(self) -> None: ...
