# app/src/module/ledhat/ledhat_hardware.py
from typing import Protocol

class LedHatHardware(Protocol):
    def clear(self) -> None: ...
    def start_animation(self, animation_name: str, **kwargs) -> None: ...
    def stop_animation(self) -> None: ...
    def cleanup(self) -> None: ...
