# app/src/module/motor/motor_hardware.py
from typing import Protocol

class MotorHardware(Protocol):
    def forward(self, speed: float) -> None: ...
    def backward(self, speed: float) -> None: ...
    def stop(self) -> None: ...
    def cleanup(self) -> None: ...
